nodejs:
  - "6"
  - "8"
os:
  - ubuntu/trusty64
cassandra:
  - dse-5.0
  - dse-5.1
build:
  - npm: install
  - script: |
      export TEST_DSE_VERSION=$CCM_VERSION
      export TEST_DSE_BRANCH=$CCM_BRANCH
      export TEST_DSE_DIR=$CCM_INSTALL_DIR
      export JAVA_HOME=$CCM_JAVA_HOME
      export CCM_PATH=$HOME/ccm
      export JUNIT_REPORT_STACK=1
      export JUNIT_REPORT_PATH=.
      export TEST_TRACE="on"
      npm run-script ci || true
  - xunit: "*.xml"
